engines:
  eslint:
    enabled: true
    config:
      config: .eslintrc.json

  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
exclude_patterns:
- "/src/**/*.test.js"
- "testeFuncional/"

