language: node_js
cache:
  yarn: true
  directories:
  - "node_modules"
node_js: '8'
jobs:
  include:
  - stage: lint
    script:
      - yarn run build-css
      - yarn lint
  - stage: unit tests
    script: yarn test-coverage
  - stage: deploy
    before_script:
      - yarn run build-css 
      - yarn build
  
